---
name: CI - Repository

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  pinned-actions:
    name: Call Ensure SHA Pinned Actions
    uses: mighty-muffin/.github/.github/workflows/reusable-ensure-pin-actions.yml@0c4ea4fff647b91e2c2a2e6da71072cfbb2192b2 # main

  repo-branch:
    name: Call Repository Branch Checks
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-branch.yml@0c4ea4fff647b91e2c2a2e6da71072cfbb2192b2 # main

  repo-file:
    name: Call Repository File Checks
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-file.yml@0c4ea4fff647b91e2c2a2e6da71072cfbb2192b2 # main

  repo-sast:
    name: Call Repository SAST Checks
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-sast.yml@0c4ea4fff647b91e2c2a2e6da71072cfbb2192b2 # main

  repo-security:
    name: Call Repository Misconfigurations
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-security.yml@0c4ea4fff647b91e2c2a2e6da71072cfbb2192b2 # main

    permissions:
      security-events: write
      contents: read
