---
name: CI - Repository

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  security-events: write
  contents: read

jobs:

  repo-security:
    name: Check Repo Security
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-security.yml@main

  pinned-actions:
    needs:
      - repo-security
    name: Check Repo Workflow
    uses: mighty-muffin/.github/.github/workflows/reusable-ensure-pin-actions.yml@main

  repo-branch:
    needs:
      - repo-security
    name: Check Repo Configuration
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-branch.yml@main

  repo-file:
    needs:
      - repo-security
    name: Check Repo Configuration
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-file.yml@main

  repo-ruleset:
    needs:
      - repo-security
    name: Check Repo Configuration
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-ruleset.yml@main

  repo-sast:
    needs:
      - pinned-actions
      - repo-ruleset
    name: Check Repo Toolchain
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-sast.yml@main

  repo-sca:
    needs:
      - pinned-actions
      - repo-ruleset
    name: Check Repo Toolchain
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-sca.yml@main

  repo-secret:
    needs:
      - pinned-actions
      - repo-ruleset
    name: Check Repo Toolchain
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-secret.yml@main
