---
name: CI - Repository

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  security-events: write
  contents: read

jobs:

  pinned-actions:
    name: Call Ensure SHA Pinned Actions
    uses: mighty-muffin/.github/.github/workflows/reusable-ensure-pin-actions.yml@main

  repo-branch:
    name: Call Repository Branch Checks
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-branch.yml@main

  repo-file:
    name: Call Repository File Checks
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-file.yml@main

  repo-sast:
    name: Call Repository SAST Checks
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-sast.yml@main

  repo-security:
    name: Call Repository Misconfigurations
    uses: mighty-muffin/.github/.github/workflows/reusable-repo-security.yml@main
