---
name: Reusable - Runner Terraform

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

jobs:
  cd-tf:
    name: Runner - Terraform
    runs-on: ubuntu-latest
    # runs-on: "self-hosted"
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
