---
name: Reusable - Run Software Composition Analysis

on: # yamllint disable-line rule:truthy
  workflow_call:


jobs:
  sca:
    name: Run SCA
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run a one-line script
        run: echo Hello, world!
        shell: bash
