---
name: Reusable - Run Snyk Scan

on: # yamllint disable-line rule:truthy
  workflow_call:
    secrets:
      SNYK_TOKEN:
        description: Snyk Token
        required: true

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@b98d498629f1c368650224d6d212bf7dfa89e4bf # 0.4.0

        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        with:
          args: --severity-threshold=high
