---
name: Reusable - Run Sonarqube Scan

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      sonarqube_gating:
        description: Enable Sonarqube Quality Gate
        required: false
        type: boolean
        default: true
    secrets:
      TAILSCALE_AUTHKEY:
        description: Tailscale Auth Key
        required: true
      SONAR_TOKEN:
        description: SonarQube Token
        required: true
      SONAR_HOST_URL:
        description: SonarQube Host URL
        required: true

jobs:
  sonarqube:
    name: Sonarqube Scan
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Connect Tailscale VPN
        uses: tailscale/github-action@84a3f23bb4d843bcf4da6cf824ec1be473daf4de # v3.2.3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: "tag:ci"
          version: "latest"
          use-cache: "true"

      - name: Run SAST - SonarQube
        uses: SonarSource/sonarqube-scan-action@2500896589ef8f7247069a56136f8dc177c27ccf # v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Quality gating SAST - SonarQube
        if: ${{ inputs.sonarqube_gating }}
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # v1.2.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
