---
name: Reusable - Repository Branch Checks
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      check_workflow:
        description: "Workflow type check: gitflow, trunk, ghflow"
        required: false
        default: gitflow
        type: string

jobs:
  repo-security:
    name: Run branches checks
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Check Gitflow compliance
        if: ${{ inputs.check_workflow == 'gitflow' }}
        run: |
          git fetch --all
          non_compliant=0
          for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/); do
            # Remove origin/ prefix for local branch name
            bname="${branch#origin/}"
            # Skip HEAD and PR refs
            if [[ "$bname" == "HEAD" || "$bname" == *"pull/"* ]]; then
              continue
            fi
            # Gitflow: feature/, bugfix/, hotfix/, release/, support/, develop, main, master
            if [[ "$bname" =~ ^(feature|bugfix|hotfix|release|support|develop|main|master)(\/.+)?$ ]]; then
              echo "✅ $bname follows Gitflow nomenclature."
            else
              echo "::warning::⚠️ Branch '$bname' does not follow Gitflow nomenclature."
              non_compliant=1
            fi
          done
          if [ $non_compliant -ne 0 ]; then
            echo "::warning::Some branches do not follow Gitflow nomenclature."
          fi

      - name: Check Trunk Based Development compliance
        if: ${{ inputs.check_workflow == 'trunk' }}
        run: |
          git fetch --all
          non_compliant=0
          for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/); do
            # Remove origin/ prefix for local branch name
            bname="${branch#origin/}"
            # Skip HEAD and PR refs
            if [[ "$bname" == "HEAD" || "$bname" == *"pull/"* ]]; then
              continue
            fi
            # Trunk Based: main, master, release, hotfix, ci/*, test/*, exp/*
            if [[ "$bname" =~ ^(main|master|release|hotfix)$ ]] || [[ "$bname" =~ ^(ci|test|exp)\/.+$ ]]; then
              echo "✅ $bname follows Trunk Based Development nomenclature."
            else
              echo "::warning::⚠️ Branch '$bname' does not follow Trunk Based Development nomenclature."
              non_compliant=1
            fi
          done
          if [ $non_compliant -ne 0 ]; then
            echo "::warning::Some branches do not follow Trunk Based Development nomenclature."
          fi
