---
name: Reusable - Repository File Checks

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  security-events: write
  contents: read

jobs:
  repo-security:
    name: Run file checks
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check for .dockerignore file (only if Dockerfile exists)
        run: |
          if [ -f Dockerfile ]; then
            if [ ! -f .dockerignore ]; then
              echo "::error file=.dockerignore::❌ .dockerignore file is missing, but Dockerfile exists!"
              exit 1
            else
              echo ".dockerignore file exists."
            fi
          else
            echo "No Dockerfile found, skipping .dockerignore check."
          fi

      - name: Check for .gitignore file
        run: |
          if [ ! -f .gitignore ]; then
            echo "::error file=.gitignore::❌ .gitignore file is missing!"
            exit 1
          else
            echo ".gitignore file exists."
          fi

      - name: Check for .pre-commit-config.yaml file
        run: |
          if [ ! -f .pre-commit-config.yaml ]; then
            echo "::error file=.pre-commit-config.yaml::❌ .pre-commit-config.yaml file is missing!"
            exit 1
          else
            echo ".pre-commit-config.yaml file exists."
          fi
