---
name: Reusable - Update flux

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flux:
    name: Update flux
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@6bf37f6a560fd84982d67f853162e4b3c2235edb # v2.6.4

      - name: Check Flux for updates
        id: update
        run: |
          flux install --export > ./k8s/cluster/base/flux-system/gotk-components.yaml

          VERSION="$(flux -v)"

          echo flux_version="$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-flux
          commit-message: Update to ${{ steps.update.outputs.flux_version }}
          title: Update to ${{ steps.update.outputs.flux_version }}
          body: ${{ steps.update.outputs.flux_version }}
