---
name: Reusable - Sync Label

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Generate Token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: generate-token
        with:
          app-id: "${{ secrets.MUFFIN_BOT_APP_ID }}"
          private-key: "${{ secrets.MUFFIN_BOT_PRIVATE_KEY }}"

      - name: Sync Labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          config-file: .github/labels.yml
          token: "${{ steps.generate-token.outputs.token }}"
          delete-other-labels: true
