---
name: Reusable - Repository Mainline Checks
on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  repo-security:
    name: Run branches checks
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Get default branch
        id: default_branch
        run: |
          default_branch=$(gh repo view --json defaultBranchRef -q ".defaultBranchRef.name")
          echo "DEFAULT_BRANCH=$default_branch" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Check workflows for default branch
        run: |
          found=0
          for wf in .github/workflows/*.yml; do
            if grep -q "$DEFAULT_BRANCH" "$wf"; then
              echo "✅ $wf targets the default branch ($DEFAULT_BRANCH)."
              found=1
            fi
          done
          if [ $found -eq 0 ]; then
            echo "::error::No workflow in .github/workflows/ targets the default branch ($DEFAULT_BRANCH)!"
            exit 1
          fi
