---
name: Reusable - Release Bump
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      release_branch:
        description: Release branch to use
        type: string
        required: false
        default: "main"
      python_file:
        description: Python version to use
        type: string
        required: false
        default: ".python-version"
      python_version:
        description: Python version to use
        type: string
        required: false
        default: "3.13"

jobs:
  release-bump:
    name: Run release bump
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    if: "!startsWith(github.event.head_commit.message, 'bump:')"

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.RELEASE_PAT }}
          fetch-depth: 0

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ inputs.python_version }}

      - name: Create CHANGELOG.md and version bump
        uses: commitizen-tools/commitizen-action@5b0848cd060263e24602d1eba03710e056ef7711 # 0.24.0
        with:
          github_token: ${{ secrets.RELEASE_PAT }}
          branch: ${{ inputs.release_branch }}
