---
name: Reusable - Ensure SHA Pinned Actions

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      allowlist:
        description: Three rules to (optionally) set for tag-rules, latest, prefix, and suffix
        required: false
        type: string
        default: |
            mighty-muffin/

jobs:
  pinned-actions:
    name: Ensure SHA Pinned Actions
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@fc87bb5b5a97953d987372e74478de634726b3e5 # v3.0.25
        with:
          allowlist: |
            ${{ inputs.allowlist }}
