---
name: Reusable - Pre-Commit

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      configuration_file:
        description: Pre-Commit configuration
        required: false
        default: ""
        type: string
      skips:
        description: Pre-Commit Skip
        required: false
        default: "true"
        type: string


jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.13'

      - name: Set python environment variable
        run: |
          echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit | ${{ env.PY }} | ${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          SKIP: ${{ inputs.skips }}
        with:
          extra_args: ${{ inputs.configuration_file }}
