---
name: Reusable - Repository Misconfigurations

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  security-events: write
  contents: read

jobs:
  repo-security:
    name: Run poutine
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Poutine security scan
        uses: boostsecurityio/poutine-action@84c0a0d32e8d57ae12651222be1eb15351429228 # v0.15.2

      - name: Upload SARIF file
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: Poutine_Security_Scan.sarif
          path: results.sarif
