---
name: Reusable - Repository SAST Checks
on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  repo-security:
    name: Run SAST checks
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Check if main.yml calls SAST workflow
        run: |
          if ! grep -q "sast" .github/workflows/main.yml; then
            echo "::error file=.github/workflows/main.yml::❌ main.yml does not call the SAST action (reusable-repo-sast)!"
            exit 1
          else
            echo "✅ main.yml calls the SAST action."
          fi
