---
name: Reusable - Run Snyk Scan

on: # yamllint disable-line rule:truthy
  workflow_call:
    secrets:
      SNYK_TOKEN:
        description: Snyk Token
        required: true

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@b98d498629f1c368650224d6d212bf7dfa89e4bf # 0.4.0

        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        with:
          args: --severity-threshold=high
