---
name: Reusable - Run Sonarqube Scan

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      sonarqube_gating:
        description: Enable Sonarqube Quality Gate
        required: false
        type: boolean
        default: true
    secrets:
      TAILSCALE_AUTHKEY:
        description: Tailscale Auth Key
        required: true
      SONAR_TOKEN:
        description: SonarQube Token
        required: true
      SONAR_HOST_URL:
        description: SonarQube Host URL
        required: true

jobs:
  sonarqube:
    name: Sonarqube Scan
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Connect Tailscale VPN
        uses: tailscale/github-action@6cae46e2d796f265265cfcf628b72a32b4d7cade # v3.3.0
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: "tag:ci"
          version: "latest"
          use-cache: "true"

      - name: Run SAST - SonarQube
        uses: SonarSource/sonarqube-scan-action@2f77a1ec69fb1d595b06f35ab27e97605bdef703 # v5.3.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Quality gating SAST - SonarQube
        if: ${{ inputs.sonarqube_gating }}
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # v1.2.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
