---
name: Reusable - Sync Label

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: generate-token
        with:
          app-id: "${{ secrets.IRISHLAB_BOT_APP_ID }}"
          private-key: "${{ secrets.IRISHLAB_BOT_PRIVATE_KEY }}"

      - name: Sync Labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          config-file: .github/labels.yml
          token: "${{ steps.generate-token.outputs.token }}"
          delete-other-labels: true
