---
name: Reusable - Repository Ruleset Checks
on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  repo-security:
    name: Run Ruleset checks
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: List all active branch protection rulesets
        id: branch_rulesets
        run: |
          echo "Active branch protection rulesets:"
          rules=$(gh api repos/${{ github.repository }}/rulesets --jq '.[] | select(.enforcement=="active" and .target=="branch") | {name: .name, enforcement: .enforcement, bypass_actors: .bypass_actors}')
          if [ -z "$rules" ]; then
            echo "::error repository configuration::❌No active branch protection rulesets found."
          else
            echo "$rules"
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: List all active tag protection rulesets
        id: tag_rulesets
        run: |
          echo "Active tag protection rulesets:"
          rules=$(gh api repos/${{ github.repository }}/rulesets --jq '.[] | select(.enforcement=="active" and .target=="tag") | {name: .name, enforcement: .enforcement, bypass_actors: .bypass_actors}')
          if [ -z "$rules" ]; then
            echo "::error repository configuration::❌No active tag protection rulesets found."
          else
            echo "$rules"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
