---
name: Reusable - Docker Scan

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      attest-enable:
        description: Create an attestion build provenance with image tags and labels
        required: false
        default: false
        type: boolean
      image-names:
        description: A list of the account/repo names for docker build to push to
        required: false
        type: string
        default: |
          ghcr.io/${{ github.repository }}

permissions:
  contents: read

jobs:

  docker-build-push:

    name: Docker - Build
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
