---
name: Reusable - Run Sonarqube Scan

on: # yamllint disable-line rule:truthy
  workflow_call:
    secrets:
      TAILSCALE_AUTHKEY:
        description: Tailscale Auth Key
        required: true
      SONAR_TOKEN:
        description: SonarQube Token
        required: true
      SONAR_HOST_URL:
        description: SonarQube Host URL
        required: true

jobs:
  sonarqube:
    name: Sonarqube Scan
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Connect Tailscale VPN
        uses: tailscale/github-action@v3.2.1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Run SAST - SonarQube
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Quality gating SAST - SonarQube
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
