---
name: Reusable - Repository Misconfigurations

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  security-events: write
  contents: read

jobs:
  repo-security:
    name: Run poutine
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Poutine security scan
        uses: boostsecurityio/poutine-action@84c0a0d32e8d57ae12651222be1eb15351429228 # v0.15.2

      - name: Upload SARIF file
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Poutine_Security_Scan.sarif
          path: results.sarif
