---
name: Reusable - Ansible Lint

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      configuration_file:
        description: Pre-Commit configuration
        required: false
        default: ""
        type: string

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.13'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: ${{ inputs.configuration_file }}
