---
name: Reusable - Repository File Checks

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  security-events: write
  contents: read

jobs:
  repo-security:
    name: Run file checks
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Check for CODEOWNERS file
        run: |
          if [ ! -f .github/CODEOWNERS ]; then
            echo "::warning file=.github/CODEOWNERS::⚠️ CODEOWNERS file is missing!"
          else
            echo "CODEOWNERS file exists."
          fi

      - name: Check for .dockerignore file (only if Dockerfile exists)
        run: |
          if [ -f Dockerfile ]; then
            if [ ! -f .dockerignore ]; then
              echo "::warning file=.dockerignore::⚠️ .dockerignore file is missing, but Dockerfile exists!"
             else
              echo ".dockerignore file exists."
            fi
          else
            echo "No Dockerfile found, skipping .dockerignore check."
          fi

      - name: Check for .gitignore file
        run: |
          if [ ! -f .gitignore ]; then
            echo "::warning file=.gitignore::⚠️ .gitignore file is missing!"
          else
            echo ".gitignore file exists."
          fi

      - name: Check for .pre-commit-config.yaml file
        run: |
          if [ ! -f .pre-commit-config.yaml ]; then
            echo "::warning file=.pre-commit-config.yaml::⚠️ .pre-commit-config.yaml file is missing!"
          else
            echo ".pre-commit-config.yaml file exists."
          fi
