---
name: Reusable - Trivy Image Scan

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      image:
        description: Image to scan
        required: true
        type: string
        # default: |
        #   ghcr.io/${{ github.repository }}:${{ github.sha }}
      exit-code:
        description: 1 if you want job to fail when CVEs are found
        required: false
        type: string
        default: |
          0
      severity:
        description: Comma delimited list of severities to scan for UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
        required: false
        type: string
        default: |
          HIGH,CRITICAL
      ignore-unfixed:
        description: Ignore unpatched/unfixed vulnerabilities
        required: false
        type: boolean
        default: true

jobs:
  build:
    name: Trivy - Image Scan

    runs-on: ubuntu-latest

    permissions: read-all

    steps:

      - name: Which image are we scanning?
        run: |
          echo "Image to scan: ${{ inputs.image }}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: ${{ inputs.image }}
          format: sarif
          output: 'trivy-results.sarif'
          exit-code: 0
          ignore-unfixed: false
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"
          timeout: 10m0s

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
