---
name: Reusable - Pre-Commit

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      configuration_file:
        description: Pre-Commit configuration
        required: false
        default: ""
        type: string
      skips:
        description: Pre-Commit Skip
        required: false
        default: "true"
        type: string


jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.14'

      - name: Set python environment variable
        run: |
          echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit | ${{ env.PY }} | ${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          SKIP: ${{ inputs.skips }}
        with:
          extra_args: ${{ inputs.configuration_file }}
