---
name: Test Workflow

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Run test
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Run nslookup
        run: |
          nslookup 192.168.1.253
          nslookup vip.local.irishlab.io
        shell: bash

      - name: Run di
        run: |
          dig 192.168.1.253
          dig vip.local.irishlab.io
        shell: bash
